[phases.setup]
aptPkgs = [
  "libxcb1",
  "libxcb-shm0",
  "libxcb-xfixes0",
  "libxcb-render0",
  "libgl1-mesa-glx",
  "libglib2.0-0",
  "libsm6",
  "libxext6",
  "libxrender-dev",
  "libgomp1",
  "libgthread-2.0-0",
  "libxi6",
  "libxtst6",
  "ffmpeg"
]

[phases.build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]
